//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTest.Build.VersionControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationTest.Build.VersionControl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $int = 1
        ///
        ///&amp; git init Repo
        ///cd repo
        ///Add-Content -Path &quot;master.txt&quot; -Value  &quot;Some text&quot;
        ///&amp; git add &quot;master.txt&quot;
        ///&amp; git commit -m &quot;$(++$i) Added master.txt&quot;
        ///
        ///Add-Content -Path &quot;master.txt&quot; -Value  &quot;Some more&quot;
        ///&amp; git add &quot;master.txt&quot;
        ///&amp; git commit -m &quot;$(++$i) Modified master.txt&quot;
        ///
        ///Add-Content -Path &quot;master.txt&quot; -Value  &quot;Some more!&quot;
        ///&amp; git add &quot;master.txt&quot;
        ///&amp; git commit -m &quot;$(++$i) Modified master.txt&quot;
        ///
        ///# Create saturn branch
        ///&amp; git checkout -b &quot;saturn&quot;
        ///Add-Content -Path &quot;saturn.txt&quot; -Value  &quot;Some text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommitGraphWalking {
            get {
                return ResourceManager.GetString("CommitGraphWalking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp; git init Repo
        ///cd repo
        ///Add-Content -Path &quot;master.txt&quot; -Value  &quot;Some text&quot;
        ///&amp; git add &quot;master.txt&quot;
        ///&amp; git commit -m &quot;Added master.txt&quot;
        ///
        ///# Create saturn branch
        ///&amp; git checkout -b &quot;saturn&quot;
        ///Add-Content -Path &quot;saturn.txt&quot; -Value  &quot;Some text&quot;
        ///&amp; git add &quot;saturn.txt&quot;
        ///&amp; git commit -m &quot;Added saturn.txt&quot;
        ///
        ///Add-Content -Path &quot;saturn.txt&quot; -Value &quot;Some text more text&quot;
        ///Add-Content -Path &quot;master.txt&quot; -Value &quot;Some text more text&quot;.
        /// </summary>
        internal static string CreateRepo {
            get {
                return ResourceManager.GetString("CreateRepo", resourceCulture);
            }
        }
    }
}
