//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization.TestCases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization.TestCases.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Aderant.Framework.Presentation.AppShell;
        ///
        ///namespace UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization {
        ///    public partial class App : AppShellApplication {
        ///
        ///        private static readonly DialogService field1 = new DialogService();
        ///
        ///        public App() {
        ///        }
        ///    }
        ///
        ///
        ///    internal partial class DialogService {
        ///
        ///    }
        ///}
        ///
        ///namespace Aderant.Framework.Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCode {
            get {
                return ResourceManager.GetString("TestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Aderant.Framework.Presentation.AppShell;
        ///
        ///namespace UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization.DelegateTypeFieldFromInstanceConstructor {
        ///    public partial class App : AppShellApplication {
        ///
        ///        private readonly EventHandler&lt;object&gt; startupInvoker;
        ///
        ///        public App() {
        ///            startupInvoker += (sender, o) =&gt; { };
        ///        }
        ///
        ///    }
        ///}
        ///
        ///namespa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCode_DelegateTypeFieldFromInstanceConstructor {
            get {
                return ResourceManager.GetString("TestCode_DelegateTypeFieldFromInstanceConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Aderant.Framework.Presentation.AppShell;
        ///
        ///namespace UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization.FieldFromInstanceConstructor {
        ///    public partial class App : AppShellApplication {
        ///
        ///        private DialogService fieldFromInstanceConstructor;
        ///
        ///        public App() {
        ///            fieldFromInstanceConstructor = new DialogService();
        ///        }
        ///    }
        ///
        ///
        ///    intern [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCode_FieldFromInstanceConstructor {
            get {
                return ResourceManager.GetString("TestCode_FieldFromInstanceConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Aderant.Framework.Presentation.AppShell;
        ///
        ///namespace UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization.StaticConstructor {
        ///    public partial class App : AppShellApplication {
        ///
        ///        private static DialogService fieldFromStaticConstructor;
        ///
        ///        static App() {
        ///            fieldFromStaticConstructor = new DialogService();
        ///        }
        ///    }
        ///
        ///
        ///    internal class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCode_InStaticConstructor {
            get {
                return ResourceManager.GetString("TestCode_InStaticConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using Aderant.Framework.Presentation.AppShell;
        ///
        ///namespace UnitTest.Aderant.Build.Analyzer.Tests.MemberInitialization.StaticFieldFromInstanceConstructor {
        ///    public partial class App : AppShellApplication {
        ///
        ///        private static DialogService staticFieldFromInstanceConstructor;
        ///
        ///        public App() {
        ///            staticFieldFromInstanceConstructor = new DialogService();
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCode_StaticFieldFromInstanceConstructor {
            get {
                return ResourceManager.GetString("TestCode_StaticFieldFromInstanceConstructor", resourceCulture);
            }
        }
    }
}
