//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTest.BuildTime {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationTest.BuildTime.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AccountsPayable {
            get {
                object obj = ResourceManager.GetObject("AccountsPayable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{A66655E5-7EC3-4F74-862A-DD00CFB1CF40}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aderant_AccountsPayable {
            get {
                return ResourceManager.GetString("Aderant_AccountsPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{6088150E-455C-4EAB-8594-320FEBA365D6}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/OutputTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aderant_AccountsPayable_Library {
            get {
                return ResourceManager.GetString("Aderant_AccountsPayable_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;12.0&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;ProjectType&gt;Local&lt;/ProjectType&gt;
        ///    &lt;ProductVersion&gt;10.0.20826&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{A438AD02-5434-48D1-BA8E-B858AE8A6FDF}&lt;/ProjectGuid&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Plat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aderant_Framework {
            get {
                return ResourceManager.GetString("Aderant_Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;10.0.20826&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{B29EDE7A-286F-4056-9DBB-8A5B7665297F}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;Library&lt;/Output [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aderant_Framework_Deployment {
            get {
                return ResourceManager.GetString("Aderant_Framework_Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DependencyManifest DefaultSource=&quot;\\dfs.aderant.com\expertsuite\dev\vnext&quot;&gt;
        ///    &lt;ReferencedModules&gt;
        ///        &lt;ReferencedModule Name=&quot;Build.T4Task&quot; AssemblyVersion=&quot;1.8.0.0&quot; /&gt;
        ///        &lt;ReferencedModule Name=&quot;Libraries.Query&quot; AssemblyVersion=&quot;1.8.0.0&quot; /&gt;
        ///        &lt;ReferencedModule Name=&quot;Libraries.SoftwareFactory&quot; AssemblyVersion=&quot;1.8.0.0&quot; /&gt;
        ///    &lt;/ReferencedModules&gt;
        ///&lt;/DependencyManifest&gt;.
        /// </summary>
        internal static string DependencyManifest {
            get {
                return ResourceManager.GetString("DependencyManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DependencyManifest DefaultSource=&quot;\\dfs.aderant.com\expertsuite\dev\vnext&quot;&gt;
        ///  &lt;ReferencedModules&gt;
        ///    &lt;ReferencedModule Name=&quot;Aderant.Framework.Development&quot; /&gt;
        ///    &lt;ReferencedModule Name=&quot;Build.T4Task&quot; AssemblyVersion=&quot;1.8.0.0&quot; /&gt;
        ///    &lt;ReferencedModule Name=&quot;Libraries.Entities.Cashmanagement&quot; AssemblyVersion=&quot;1.8.0.0&quot; /&gt;
        ///    &lt;ReferencedModule Name=&quot;Libraries.Entities.Employee&quot; AssemblyVersion=&quot;1.8.0.0&quot; /&gt;
        ///    &lt;ReferencedModule Name=&quot;Libraries.Entities.Firm&quot; Ass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DependencyManifest1 {
            get {
                return ResourceManager.GetString("DependencyManifest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DependencyManifest DefaultSource=&quot;\\dfs.aderant.com\expertsuite\dev\vnext&quot;&gt;&gt;
        ///    &lt;ReferencedModules&gt;
        ///    &lt;/ReferencedModules&gt;
        ///&lt;/DependencyManifest&gt;.
        /// </summary>
        internal static string DependencyManifest2 {
            get {
                return ResourceManager.GetString("DependencyManifest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Deployment {
            get {
                object obj = ResourceManager.GetObject("Deployment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Framework {
            get {
                object obj = ResourceManager.GetObject("Framework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Library {
            get {
                object obj = ResourceManager.GetObject("Library", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] paket {
            get {
                object obj = ResourceManager.GetObject("paket", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] paket1 {
            get {
                object obj = ResourceManager.GetObject("paket1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] paket2 {
            get {
                object obj = ResourceManager.GetObject("paket2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TFSBuild {
            get {
                object obj = ResourceManager.GetObject("TFSBuild", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TFSBuild1 {
            get {
                object obj = ResourceManager.GetObject("TFSBuild1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TFSBuild2 {
            get {
                object obj = ResourceManager.GetObject("TFSBuild2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
