//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationTest.Build.EndToEnd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegrationTest.Build.EndToEnd.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-StrictMode -Version &apos;Latest&apos;
        ///
        ///&amp; git init .
        ///
        ///[string]$cwd = Get-Location
        ///$file = $cwd + &apos;\.gitignore&apos;
        ///
        ///[System.IO.File]::WriteAllLines($file, @&apos;
        ///[Bb]in/
        ///[Oo]bj/
        ///&apos;@)
        ///
        ///&amp; git add &apos;-A&apos; &apos;-f&apos;
        ///&amp; git add &apos;ModuleA\Build\TFSBuild.rsp&apos; &apos;-f&apos;
        ///&amp; git add &apos;ModuleB\Build\TFSBuild.rsp&apos; &apos;-f&apos;
        ///&amp; git commit -m &apos;Added all files&apos;.
        /// </summary>
        internal static string CreateRepo {
            get {
                return ResourceManager.GetString("CreateRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RunSettings&gt;
        ///  &lt;RunConfiguration&gt;
        ///    &lt;MaxCpuCount&gt;4&lt;/MaxCpuCount&gt;
        ///    &lt;TestSessionTimeout&gt;1200000&lt;/TestSessionTimeout&gt;
        ///  &lt;/RunConfiguration&gt;
        ///  &lt;!-- MSTest adapter --&gt;
        ///  &lt;MSTest&gt;
        ///    &lt;MapInconclusiveToFailed&gt;True&lt;/MapInconclusiveToFailed&gt;
        ///    &lt;CaptureTraceOutput&gt;true&lt;/CaptureTraceOutput&gt;
        ///    &lt;DeleteDeploymentDirectoryAfterTestRunIsComplete&gt;false&lt;/DeleteDeploymentDirectoryAfterTestRunIsComplete&gt;
        ///    &lt;DeploymentEnabled&gt;true&lt;/DeploymentEnabled&gt;
        ///    &lt;AssemblyR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Expected_run_settings {
            get {
                return ResourceManager.GetString("Expected_run_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RunSettings&gt;
        ///&lt;/RunSettings&gt;.
        /// </summary>
        internal static string my_custom_runsettings {
            get {
                return ResourceManager.GetString("my_custom_runsettings", resourceCulture);
            }
        }
    }
}
